export const SET_ALERT = 'SET_ALERT';

export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';

export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';

export const PROFILE_ERROR = 'GET_ERROR';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SEARCH_BUSINESS = 'SEARCH_BUSINESS';

export const LOAD_MORE = 'LOAD_MORE'

export const GET_BUSINESS_DETAIL = 'GET_BUSINESS_DETAIL';

export const GET_BUSINESS_REVIEWS = 'GET_BUSINESS_REVIEWS';

export const SEARCH_FAIL = 'SEARCH_FAIL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';

export const GET_ALL_APPOINTMENTS = 'GET_ALL_APPOINTMENTS';

export const SET_SERVICE = 'SET_SERVICE';

export const SET_STAFF = 'SET_STAFF';

export const SET_DATE_TIME = 'SET_DATE_TIME';

export const RESET_APPOINTMENT = 'RESET_APPOINTMENT';




